name: 'Setup Cached Cask'
description: 'Setup cached Cask for Github Actions workflow'

inputs:
  checkout-path:
    description: >
      The value of relative path under $GITHUB_WORKSPACE where the repository
      has been checked out.

  emacs-version:
    description: >
      The version of Emacs to create the cache for, for example: 30.1,
      snapshot.  If the value is "snapshot" then use latest commit hash found
      in https://github.com/purcell/nic-emacs-ci repository.  If the value is
      not specified then use version from "cask emacs --version".

  cask-version:
    description: >
      The version of Cask to use. See https://github.com/cask/setup-cask.
    default: 'snapshot'

outputs:
  key:
    description: >
      A key used for the created cache for Cask packages.
    value: ${{ steps.get-cache-key.outputs.key }}

runs:
  using: "composite"
  steps:

    - name: Setup Cask
      uses: cask/setup-cask@master
      with:
        version: ${{ inputs.cask-version }}

    - name: Get cache key
      id: get-cache-key
      shell: bash
      run: |
        echo "key=$(${{ github.action_path }}/get-cache-key.sh \
                        ${{ github.workspace }}/${{ inputs.checkout-path }} \
                        ${{ inputs.emacs-version }})" \
            >> "$GITHUB_OUTPUT"

    - name: Print cache key
      shell: bash
      run: |
        echo "Using cache key for cask packages: ${{ steps.get-cache-key.outputs.key }} "

    - name: 'Cache Cask packages'
      uses: actions/cache@v4
      with:
        path: .cask
        key: ${{ steps.get-cache-key.outputs.key }}
