name: 'Setup Cached Cask'
description: 'Setup cached Cask for Github Actions workflow'

inputs:
  checkout-path:
    description: >
      The value of relative path under $GITHUB_WORKSPACE where the repository
      has been checked out.

  emacs-version:
    description: >
      The version of Emacs to create the cache for, for example: 30.1,
      snapshot.  If the value is "snapshot" then use latest commit hash found
      in https://github.com/purcell/nic-emacs-ci repository.  If the value is
      not specified then use version from "cask emacs --version".

  cask-version:
    description: >
      The version of Cask to use. See https://github.com/cask/setup-cask.
    default: 'snapshot'

  cask-filename:
    description: >
      The name of Cask file to use
    default: 'Cask'

outputs:
  key:
    description: >
      A key used for the created cache for Cask packages.
    value: ${{ steps.get-cache-key.outputs.key }}

  cache-hit:
    description: >
      A boolean value to indicate an exact match was found for the primary key.
    value: ${{ steps.cache-hit.outputs.cache-hit }}

runs:
  using: "composite"
  steps:

    - name: Setup Cask
      uses: cask/setup-cask@master
      with:
        version: ${{ inputs.cask-version }}

    - name: Get cache key
      id: get-cache-key
      shell: bash
      run: |
        echo "key=$(${{ github.action_path }}/get-cache-key.sh \
                        ${{ github.workspace }}/${{ inputs.checkout-path }} \
                        ${{ inputs.emacs-version }})" \
            >> "$GITHUB_OUTPUT"
      env:
        CASK_CACHE_FILE_NAME: ${{ inputs.cask-filename }}

    - name: Cache Cask packages
      id: cache-cask-packages
      uses: actions/cache@v4
      with:
        path: .cask
        key: ${{ steps.get-cache-key.outputs.key }}

    - name: Set cache-hit
      id: cache-hit
      shell: bash
      run: |
        echo "cache-hit=${{ steps.cache-cask-packages.outputs.cache-hit }}" \
            >> "$GITHUB_OUTPUT"
